# Generated by Django 4.2.20 on 2025-04-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('attendence_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendence_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('costcenter_id', models.AutoField(primary_key=True, serialize=False)),
                ('costcenter_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocationCostCentre',
            fields=[
                ('location_costcentre_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_costcentre_desc', models.CharField(max_length=100)),
                ('costcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.costcentre')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='LTA',
            fields=[
                ('lta_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lta_type', models.CharField(max_length=100)),
                ('supplier_type', models.CharField(max_length=100)),
                ('supplier_desc', models.CharField(max_length=255)),
                ('lta_start_date', models.DateField()),
                ('lta_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_contact_address', models.TextField()),
                ('staff_mobile', models.CharField(max_length=20)),
                ('profile_desc', models.CharField(max_length=100)),
                ('costcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.costcentre')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.country')),
                ('location_costcentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.locationcostcentre')),
            ],
        ),
        migrations.CreateModel(
            name='StaffingCategory',
            fields=[
                ('staffing_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('staffing_category_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('focal_person', models.CharField(blank=True, max_length=100, null=True)),
                ('present', models.BooleanField(default=False)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('overnight', models.BooleanField(default=False)),
                ('cra', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.staffdetails')),
            ],
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.staffprofile'),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.region'),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_desc', models.CharField(max_length=100)),
                ('wage_rate_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overnight_rate_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('int_dsa_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance_presidential_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lta_number', models.CharField(max_length=100)),
                ('lta_type', models.CharField(max_length=100)),
                ('supplier_type', models.CharField(max_length=100)),
                ('supplier_desc', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.staffprofile')),
            ],
        ),
        migrations.AddField(
            model_name='locationcostcentre',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.region'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('access_level', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.region')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.region'),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.country'),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.region'),
        ),
    ]
