# Generated by Django 4.2.20 on 2025-04-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0002_alter_attendancetype_attendence_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffdetails',
            options={'verbose_name': 'Staff detail', 'verbose_name_plural': 'Staff details'},
        ),
        migrations.RemoveField(
            model_name='rate',
            name='lta_number',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='lta_type',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='supplier_desc',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='supplier_type',
        ),
        migrations.AddField(
            model_name='rate',
            name='cra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='lta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.lta'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='allowance_presidential_per_day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rate',
            name='int_dsa_per_day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rate',
            name='overnight_rate_per_day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rate',
            name='overtime_rate_per_hour',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rate',
            name='wage_rate_per_day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staff_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
